version: '3.9'

services:
  git_webhook:
    container_name: "git_webhook"
    hostname: "webhook"
    build:
      context: "git_webhook/"
      network: host
      args:
        - REPO_URL
        - GIT_SSH_KEY
        - DFU_PUBLIC_KEY_C
        - DFU_PRIVATE_KEY
        - KEY_PATH
        - APP_PATH
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - repo:/root/repo
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  dfu_server:
    container_name: "dfu_server"
    hostname: "dfu"
    build:
      context: "dfu_server/"
      network: host
    ports:
      - "5683:5683/udp"
      - "5684:5684/udp"
    depends_on:
      - "git_webhook"
    env_file:
      - .env
    volumes:
      - repo:/root/repo
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  repo:

